version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  helm: circleci/helm@1.0

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: |
          cd cuquejo.org
          yarn install
          yarn test --watchAll=false

  build-and-push:
    machine:
      image: ubuntu-2004:202107-02
    environment:
      DOCKER_BUILDKIT: 1
      REGISTRY_URL: us-central1-docker.pkg.dev
      TAG: 1.0.1
    steps:
      - checkout
      - run: ./.circleci/setup_gcloud.sh
      - run: gcloud auth configure-docker --quiet $REGISTRY_URL
      - run: make build-ci
      - run: make push-ci

  deploy:
    docker:
      - image: cimg/base:stable
    environment:
      REGISTRY_URL: us-central1-docker.pkg.dev
      TAG: 1.0.1
    steps:
      - checkout
      - run: ./.circleci/setup_gcloud.sh
      - run: ./.circleci/setup_kubectl_helm.sh
      - run: helm upgrade --install --namespace cuquejo --set image.url=${REGISTRY_URL}/${GOOGLE_PROJECT_ID}/cuquejo/${CIRCLE_PROJECT_REPONAME}:${TAG} cuquejo-org .

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push
