version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  gcp-gcr: circleci/gcp-gcr@0.13.0

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: |
          cd cuquejo.org
          yarn install
          yarn test --watchAll=false
    # Example Using docker build
    # machine:
    #   image: ubuntu-2004:202107-02
    # steps:
    #   - checkout
    #   - run: make test
  build-and-push:
    executor: gcp-gcr/default
    environment:
     DOCKER_BUILDKIT: 1
     REGISTRY_URL: us-central1-docker.pkg.dev
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          dockerfile:  docker/Dockerfile
          extra_build_args: "--target=prod"
          image: cuquejo/${CIRCLE_PROJECT_REPONAME}
          tag: ${CIRCLE_TAG}
          registry-url: ${REGISTRY_URL}

      - run: docker image ls && docker push ${REGISTRY_URL}/$GOOGLE_PROJECT_ID/cuquejo/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
      # - gcp-gcr/push-image:
      #     image: cuquejo/${CIRCLE_PROJECT_REPONAME}
      #     tag: ${CIRCLE_TAG}
      #     registry-url: ${REGISTRY_URL}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build-and-push:
          filters:
            tags:
              only: /.*/