version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  gcr: circleci/gcp-gcr@0.0.2

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: yarn test --watchAll=false
  build-and-push:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          dockerfile:  docker/Dockerfile
          extra_build_args: "--target=prod"
          image: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
          registry-url: us-central1-docker.pkg.dev/regal-reporter-298211/cuquejo/

      - gcr/push-image:
          image: ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
          registry-url: us-central1-docker.pkg.dev/regal-reporter-298211/cuquejo/

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build-and-push