version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  # gcp-gcr: circleci/gcp-gcr@0.13.0

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: |
          cd cuquejo.org
          yarn install
          yarn test --watchAll=false

  build-and-push:
    machine:
      image: ubuntu-2004:202107-02
    environment:
      DOCKER_BUILDKIT: 1
      REGISTRY_URL: us-central1-docker.pkg.dev
      TAG: v.0.1
    steps:
      - checkout
      - run: ./.circleci/setup_gcloud.sh
      - run: gcloud auth configure-docker --quiet $REGISTRY_URL
      - run: docker pull busybox
      - run: docker tag busybox us-central1-docker.pkg.dev/regal-reporter-298211/cuquejo/cuquejo.org:latest
      - run: docker push us-central1-docker.pkg.dev/regal-reporter-298211/cuquejo/cuquejo.org:latest

  # Uisng ORBS
  # build-and-push:
  #   executor: gcp-gcr/default
  #   environment:
  #    DOCKER_BUILDKIT: 1
  #    REGISTRY_URL: us-central1-docker.pkg.dev
  #    TAG: v.0.1
  #   steps:
  #     - checkout
  #     - gcp-gcr/gcr-auth
  #     - gcp-gcr/build-image:
  #         dockerfile:  docker/Dockerfile
  #         extra_build_args: "--target=prod"
  #         image: cuquejo/${CIRCLE_PROJECT_REPONAME}
  #         tag: ${CIRCLE_TAG}
  #         registry-url: ${REGISTRY_URL}

  #     - gcp-gcr/push-image:
  #         image: cuquejo/${CIRCLE_PROJECT_REPONAME}
  #         tag: ${CIRCLE_TAG}
  #         registry-url: ${REGISTRY_URL}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            tags:
              only: /.*/