version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
  gcp-gcr: circleci/gcp-gcr@0.13.0

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run: |
          cd cuquejo.org
          yarn install
          yarn test --watchAll=false

  build-and-push:
    machine:
      image: ubuntu-2004:202107-02
    environment:
      DOCKER_BUILDKIT: 1
      REGISTRY_URL: us-central1-docker.pkg.dev
      TAG: v.0.1
    steps:
      - checkout
      - run: |
          echo "Setup gcloud:"
          apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          apt-get update && apt-get install google-cloud-sdk
          echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project $GOOGLE_PROJECT_ID
          gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
          gcloud --quiet config set compute/region $GOOGLE_COMPUTE_REGION
          echo "Setup GCR:"
          gcloud auth configure-docker --quiet $REGISTRY_URL
          docker pull busybox
          docker tag busybox us-central1-docker.pkg.dev/regal-reporter-298211/cuquejo/cuquejo.org:latest


  # build-and-push:
  #   executor: gcp-gcr/default
  #   environment:
  #    DOCKER_BUILDKIT: 1
  #    REGISTRY_URL: us-central1-docker.pkg.dev
  #    TAG: v.0.1
  #   steps:
  #     - checkout
  #     - gcp-gcr/gcr-auth
  #     - gcp-gcr/build-image:
  #         dockerfile:  docker/Dockerfile
  #         extra_build_args: "--target=prod"
  #         image: cuquejo/${CIRCLE_PROJECT_REPONAME}
  #         tag: ${CIRCLE_TAG}
  #         registry-url: ${REGISTRY_URL}

  #     - gcp-gcr/push-image:
  #         image: cuquejo/${CIRCLE_PROJECT_REPONAME}
  #         tag: ${CIRCLE_TAG}
  #         registry-url: ${REGISTRY_URL}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build-and-push:
          filters:
            tags:
              only: /.*/